name: Generate TTL

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Generate a TTL file
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Fetch data
      run: ./fetch_data.sh
    - name: Generate TTL
      run: ./xml2arche.py
     - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Export and Transformation done
